// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqGw9jTP8azYFvb3tv1YYuXQf5SjxoVWA',
    appId: '1:369411867126:web:af1844953caca2cafa47d7',
    messagingSenderId: '369411867126',
    projectId: 'odtusocial-a15f7',
    authDomain: 'odtusocial-a15f7.firebaseapp.com',
    storageBucket: 'odtusocial-a15f7.appspot.com',
    measurementId: 'G-SY0FQR2TSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKvfn2HEP7Q5vHwaLLq8DlwGV5aUZVqyA',
    appId: '1:369411867126:android:011588e6727a644afa47d7',
    messagingSenderId: '369411867126',
    projectId: 'odtusocial-a15f7',
    storageBucket: 'odtusocial-a15f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_0d5i-YxjYWjhKfJfqvxHV__N0wjxAd4',
    appId: '1:369411867126:ios:945f9f9a74608f53fa47d7',
    messagingSenderId: '369411867126',
    projectId: 'odtusocial-a15f7',
    storageBucket: 'odtusocial-a15f7.appspot.com',
    iosClientId: '369411867126-hf66ki1s5lpgsnfl559pto1k7aqemacu.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_0d5i-YxjYWjhKfJfqvxHV__N0wjxAd4',
    appId: '1:369411867126:ios:945f9f9a74608f53fa47d7',
    messagingSenderId: '369411867126',
    projectId: 'odtusocial-a15f7',
    storageBucket: 'odtusocial-a15f7.appspot.com',
    iosClientId: '369411867126-hf66ki1s5lpgsnfl559pto1k7aqemacu.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );
}
